[versions]
kotlin = "2.0.21"
kotlinx-serialization = "1.7.3"
aws-sdk = "1.4.25"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
aws-dynamodb = { module = "aws.sdk.kotlin:dynamodb", version.ref = "aws-sdk" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:14.0.1"
maven-publish = "com.vanniktech.maven.publish:0.35.0"
