[versions]
kotlin = "2.0.21"
kotlinx-serialization = "1.7.3"
aws-dynamodb = "1.4.25"
ktlint = "14.0.1"
maven-central-publish = "1.3.0"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
aws-dynamodb = { module = "aws.sdk.kotlin:dynamodb", version.ref = "aws-dynamodb" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
maven-central-publish = { id = "tech.yanand.maven-central-publish", version.ref = "maven-central-publish" }
